variable:
  profiles : pro

server:
  port: 8080

#配置日志文件输出路径、指定文件名
#path和name不能同时配置，同时配置时，以文件为准
logging:
  file:
    path: ./logs
    #    name: logback.log

spring:
  application:
    name: TestDemo
  #配置mysql数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://hostname/db
    username: username
    password: password

mybatis:
  #配置启动mybatis时所需的java bean的路径，用于映射
  type-aliases-package: cn.skio.crms.bean
  #配置存放sql语句的路径
  mapper-locations:
    - mapper/*

